### ISSUE TITLE
SplashScreen is always over other windows

### ISSUE THREAD

**Issue by jongonzalezr** [tom-englert/SplashScreen.Fody#1]
**Describe the bug:**
When I launch the application, the splash screen is shown above the rest of the windows. That is, even if I click on other windows or applications, the splash screen always stays on top and doesn't allow you to see what is behind (and, therefore, you cannot interact with it). When application is loaded, splash screen closes as expected.

**Expected behavior:**
Launch application and show the splash screen, but if I click on other application, let the application be shown above the splash screen.

**Environment:**
- SplashScreen.Fody v1.0.0
- Fody v4.0.0
- .NET Framework v4.6

**Comment by tom-englert** [comment]
Good point, do you have an idea how to fix this? Can you provide a PR?
