### ISSUE TITLE
SplashScreen user control not found after .NET 8 upgrade

### ISSUE THREAD

**Issue by nabrezzelt** [tom-englert/SplashScreen.Fody#10]
Hi,

after the change of the target framework from .NET 7 to .NET 8 the SplashScreen-UserControl isn't found with the following error message:

`Fody/SplashScreen: Bitmap generator failed: The project does not contain a type named 'xxx.xxx.SpashScreen'. Add a user control named xxx.xxx.SpashScreen.xaml as a template for your splash screen.	`

**Comment by nabrezzelt** [comment]
Hey, when do you plan a new release where this is fixed? :)

**Comment by tom-englert** [comment]
2.1.0 is already online
