### ISSUE TITLE
MSBUILD : error : Fody/SplashScreen: The filename or extension is too long

### ISSUE THREAD

**Issue by SmithsonianDSP** [tom-englert/SplashScreen.Fody#5]
**Describe the bug:**
After installing a new NuGet package (specifically [`ModernWpfUI`](https://github.com/Kinnara/ModernWpf)) and no other changes to the solution, build fails with the message:

```
4>FodyTarget:
4>    Fody: Fody (version 6.2.4.0 @ file:///C:/Users/<USER>/.nuget/packages/fody/6.2.4/netclassictask/Fody.dll) Executing
4>MSBUILD : warning FodyPackageReference: Fody: The package reference for SplashScreen.Fody does not contain PrivateAssets='All'
4>      Fody/SplashScreen:   Executing Weaver 
4>      Fody/SplashScreen:   Bitmap generator: C:\Users\<USER>\.nuget\packages\splashscreen.fody\2.0.2\build\..\netstandardweaver\.NETFramework\SplashGenerator.exe
4>MSBUILD : error : Fody/SplashScreen: The filename or extension is too long
4>    Fody:   Finished Fody 2448ms.
4>
4>Build FAILED.
``` 

**Expected behavior:**
Build does not fail.

**Environment:**
* SplashScreen.Fody v2.0.2
* Fody v6.2.4
* .NET Framework v4.7.2

----

Solution path length: 28 characters
Fody project path length: 36 characters
SplashScreen UserControl path length: 51

What is so unusual about this (to me) is that it occurs only after installing the new package but without referencing or using the new package anywhere in the project/solution. 

I attempted to create a new solution to reproduce the issue but it doesn't appear to be a bug specific to the new package.  Installing just the prerequisite packages does not create the error, either; only the primary package seems to create the issue in the primary Solution.  

Would appreciate any help in understanding why this occurring after adding a new package, here, since none of the other paths have changed.

**Comment by tom-englert** [comment]
Without a reproduction sample I can't tell what the problem is...
Maybe try this one, i've never experienced such a problem with it: https://github.com/tom-englert/TomsToolbox/blob/master/Documentation/Topics/TomsToolbox.Wpf.Styles.md

**Comment by SmithsonianDSP** [comment]
Is there a way that I can get more debug info or console output from Fody/SplashScreen.Fody to get a better idea of where it's occurring?

**Comment by tom-englert** [comment]
Did you try setting build output to "detailed"?

**Comment by SmithsonianDSP** [comment]
Yes, but it doesn't provide any additional information about what specific filename/path/extension is causing `SplashScreen.Fody` to error and fail. 

Interestingly, it seems that [ModernWpfUI v0.9.3](https://www.nuget.org/packages/ModernWpfUI/0.9.3) does not encounter this problem while [ModernWpfUi v0.9.4](https://www.nuget.org/packages/ModernWpfUI/0.9.4) does.  

While it isn't ideal, it does allow me to do what I needed. It still seems odd that Fody/SplashScreen is being tripped up just from a referenced NuGet package that isn't even used anywhere in the project, but I understand if you want to close what appears to be a weird edge case.
